KendoProto1/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KendoProto1.Models;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace KendoProto1.Controllers
{
    public class CountryController : Controller
    {
        // GET: Country
        public ActionResult Index()
        {
            return View();
        }

        public async Task<string> GetListAsync()
        {
            List<Country> list = await CountryCrud.GetAll();

            return JsonConvert.SerializeObject(list);
        }

        public async Task<JsonResult> Read(/*int skip, int take*/)
        {
            var list = await CountryCrud.GetAll() as IEnumerable<Country>;

            //   list = list.Skip(skip).Take(take);

            return this.Jsonp(list);
        }

        public async Task<ActionResult> Create()
        {
            List<Country> list = this.DeserializeObject<IEnumerable<Country>>("models") as List<Country>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    int Id = await CountryCrud.Add(list[i]);
                    list[i].Id = Id;
                }
            }
            return this.Jsonp(list);
        }

        public async Task<JsonResult> Update()
        {
            List<Country> list = this.DeserializeObject<IEnumerable<Country>>("models") as List<Country>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    await CountryCrud.Edit(list[i]);
                }
            }
            return this.Jsonp(list);
        }

        public async Task<JsonResult> Destroy()
        {
            List<Country> list = this.DeserializeObject<IEnumerable<Country>>("models") as List<Country>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    await StaffCrud.Del(list[i].Id);
                }
            }
            return this.Jsonp(list);
        }

        [HttpPost]
        public async Task Delete(int Id)
        {
            await CountryCrud.Del(Id);
        }

        [HttpPost]
        public async Task Edit(object model = null)
        {
            Country country = (Country)model;
            try
            {
                await CountryCrud.Edit(country);
            }
            catch(Exception ex)
            {
                string strError = ex.Message;
            }
        }
    }
}

KendoProto1/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KendoProto1.Models;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace KendoProto1.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        public ActionResult Index()
        {
            return View();
        }

        public string GetSex()
        {
            return JsonConvert.SerializeObject(StaffCrud.ArrSexList);
        }

        public JsonResult Read(/*int skip, int take*/)
        {
            var list =  StaffCrud.GetAll() as IEnumerable<Staff>;
            //   list = list.Skip(skip).Take(take);

            return this.Jsonp(list);
        }

        public async Task<ActionResult> Create()
        {
            List<StaffEdit> list = this.DeserializeObject<IEnumerable<StaffEdit>>("models") as List<StaffEdit>;
            List<Staff> list2 = new List<Staff>();

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    int Id = await StaffCrud.Add((Staff)list[i]);
                    list[i].Id = Id;
                    Staff NewStaff = await StaffCrud.GetById(Id);
                    list2.Add(NewStaff);
                }
            }

            return this.Jsonp(list2);
        }

        public async Task<JsonResult> Update()
        {
            List<Staff> list = this.DeserializeObject<IEnumerable<Staff>>("models") as List<Staff>;

            List<Staff> list2 = new List<Staff>();

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    await StaffCrud.Edit(list[i]);
                    Staff model = await StaffCrud.GetById(list[i].Id);
                    list2.Add(model);
                }
            }
            var list3 = list2 as IEnumerable<Staff>;
            return this.Jsonp(list3);
        }

        public async Task<JsonResult> Destroy()
        {
            List<StaffEdit> list = this.DeserializeObject<IEnumerable<StaffEdit>>("models") as List<StaffEdit>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    await StaffCrud.Del(list[i].Id);
                }
            }
            return this.Jsonp(list);
        }

        [HttpPost]
        public async Task Delete(int Id)
        {
           await  StaffCrud.Del(Id);
        }

        [HttpPost]
        public async Task Edit(object model = null)
        {
            Staff country = (Staff)model;
            try
            {
                await StaffCrud.Edit(country);
            }
            catch (Exception ex)
            {
                string strError = ex.Message;
            }
        }
    }
}

KendoProto1/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KendoProto1.Models;
using System.Threading.Tasks;
using System.Collections;
using Newtonsoft.Json;

namespace KendoProto1.Controllers
{
    [Authorize]
    [Authorize(Roles = "Админ")]
    public class UsersController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetAll(/*int skip, int take*/)
        {
            var list = await UsersCrud.GetAll() as IEnumerable<Users>;

            //   list = list.Skip(skip).Take(take);

            return this.Jsonp(list);
        }

        public ActionResult Add()
        {
            List<Users> list = this.DeserializeObject<IEnumerable<Users>>("models") as List<Users>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    int Id = UsersCrud.Add(list[i]);
                    list[i].Id = Id;
                }
            }
            return this.Jsonp(list);
        }

        public JsonResult Edit()
        {
            List<Users> list = this.DeserializeObject<IEnumerable<Users>>("models") as List<Users>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                     UsersCrud.Edit(list[i]);
                }
            }
            return this.Jsonp(list);
        }

        public JsonResult Del()
        {
            List<Users> list = this.DeserializeObject<IEnumerable<Users>>("models") as List<Users>;

            if (list != null)
            {
                for (int i = 0; i < list.Count(); i++)
                {
                    UsersCrud.Del(list[i].Id);
                }
            }
            return this.Jsonp(list);
        }

        public string RoleList2()
        {
            List<MyRole> list = new List<MyRole>();

            MyRole admin = new MyRole { name = "Админ" };
            list.Add(admin);

            MyRole user = new MyRole { name = "Юзер" };
            list.Add(user);

            MyRole user2 = new MyRole { name = "Юзер-2" };
            list.Add(user2);

            return JsonConvert.SerializeObject(list);
        }

        public IEnumerable RoleDrops()
        {
            List<MyRole> list = new List<MyRole>();

            MyRole admin = new MyRole {name= "Админ" };
            list.Add(admin);

            MyRole user = new MyRole { name = "Юзер" };
            list.Add(user);

            MyRole user2 = new MyRole { name = "Юзер-2" };
            list.Add(user2);

            IEnumerable<MyRole> list2 = list as IEnumerable<MyRole>;
            
             return list2;
        }

        [HttpPost]
        public void Delete(int Id){
            UsersCrud.Del(Id);
        }

        public string RoleList(string SelName, bool IsFilter = false)
        {
            List<string> list = UsersCrud.GetRoles().ToList();

            if (IsFilter)
            {
                list.Insert(0, "Все");
            }

            string result = $"<select id='{SelName}' >";

            foreach (var item in list)
            {
                result = result + "<option value = '" + item + "'>" + item + "</option>";
            }

            result = result + "</select>";
            return result;
        }

        public string RoleFilter(string SelName)
        {
            List<string> list = UsersCrud.GetRoles().ToList();

            list.Insert(0, "Все");

            string result = $"<select id='{SelName}' >";

            result = result + "<option value = ''>" + list[0] + "</option>";
            if (list.Count > 0)
            {
                for (int i = 1; i < list.Count; i++)
                {
                    result = result + "<option value = '" + list[i] + "'>" + list[i] + "</option>";
                }
            }

            result = result + "</select>";
            return result;
        }

    }

    public class MyRole
    {
      public  string name { get; set; }
    }
}

KendoProto1/Views/Shared/_Layout.cshtml
@using KendoProto1.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KendoProto1 - 2017</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.common-bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.dataviz.bootstrap.min.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.default.min.css")" rel="stylesheet" type="text/css" />

    @*<link href="@Url.Content("~/Content/kendo/2017.1.223/kendo.flat.min.css")" rel="stylesheet" type="text/css" />*@


    <script src="@Url.Content("~/Scripts/kendo/2017.1.223/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.1.223/angular.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.1.223/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2017.1.223/kendo.all.min.js")"></script>

    <script src="@Url.Content("~/Scripts/kendo.culture.ru-RU.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.messages.ru-RU.js")"></script>

    <script type="text/javascript">

        $(function () {
            kendo.culture('ru-RU');
        });

    </script>



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @Html.ActionLink("Прототип", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.Identity.GetUserRole() == "Админ")
                            {
                                <li>@Html.ActionLink("Пользователи", "Index", "Users")</li>
                            }
                            <li>@Html.ActionLink("Страны", "Index", "Country")</li>
                            <li>@Html.ActionLink("Персонал", "Index", "Staff")</li>
                        }
                       </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
    </div>

    <div class="container body-content" style="max-width:100%;">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - KendoProto1</p>
            </footer>
        </div>
        @RenderSection("scripts", required: false)
</body>
</html>